### PR TITLE
Strain fitness

### PR DESCRIPTION
**Pull request by rneher**
any reason not to merge this? Would of course be great if we could have the same of H3, but it definitely adds real information (to test, I shifted the indices of the alignment and no more information is gained)

### CODE REVIEW

**Comment by trvrb** [comment]
How big are the `Thyagarajan_Bloom_HA_fitness.txt` and `H1_H3.fasta` files? Does it make sense to include them in the repo? Should they live in a directory other than `data/`? Seems like they're source files rather than compiled intermediates the way `tree.json`, etc... is an intermediate.

**Comment by rneher** [comment]
sort of. Thyagarajan_Bloom_HA_fitness.txt is the supplementary from their elife paper. H1_H3.fasta is simply an amino acid alignment between H1 and H3 HA1. I added the two to the dropbox (which I have symlinked to augur/src/data)

**Comment by trvrb** [comment]
Thanks for adding them to dropbox. I think I'd like a new `source-data/` directory that would contain these sorts of helper files. This directory would also contain things like the mapping of strain geo label to country and region. 

Also, this way, someone else could regenerate all the results with only a GISAID download.

**Comment by rneher** [comment]
good idea!

**Comment by trvrb** [comment]
It's definitely nice to see the positive predictive performance of the `tol` predictor.

**Pull request merged**
