### PR TITLE
Treeexport

### PR DESCRIPTION
**Pull request by rneher**
there are two things that need discussion/refinement:
- positions of download/export buttons
- the behavior of the download frequencies. it currently does the same as the plot frequencies button + export. this prevents export of a clade frequency (corresponding to a branch in the tree) that might be currently displayed. this could be changed, but I am not sure what the more intuitive behavior is.

### CODE REVIEW

**Comment by trvrb** [comment]
Here's what I get when I export the tree:

export

Styling the clade annotations as San Serif should be pretty easy. Getting the cross maybe more difficult.

**Comment by rneher** [comment]
It is sans serif for me, but I guess this depends on the default. not sure how to get the font-awesome unicode. for me, the box doesn't show

**Comment by trvrb** [comment]
Interesting. I get similar behaviors with Firefox and Safari.

**Comment by rneher** [comment]
I opened the svg in inkscape. in firefox, I get the same behavior as you do. I think the issue is that the font doesn't get exported, hence it takes whatever font it wants and if the character doesn't exists puts the usual box

**Comment by rneher** [comment]
this seems to the point: 
https://groups.google.com/forum/#!topic/fabricjs/ba8mpq9N9f8
not sure what to do about it. I feel having a fully colored vector graphics output is worth the missing cross. people can adjust the font of the clade annotation if they want. explicitly setting to sans might work.

**Comment by trvrb** [comment]
You can style SVG with CSS (obviously). So, it should work just wrapping the export with `font-family: Helvetica; Sans Serif;`. I agree that the cross is not worth pursuing.

**Pull request closed without merging**
