### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by rneher**
## Major reorganisation

all H3N2 specific parts are now in H3N2_process.py. The central object is a class `H3N2_process` that inherits a generic process class together with a `filter, clean, tree_refine, frequency` classes. All parameters and arguments are percolated through the structure using keyword arguments (**kwargs). A few parameters might still be lingering here and there. the `delimit_newick` is still influenza A specific. 
### Usage

`python src/H3N2_process -y 3 -v 20 --prefix data/test_`

would run the pipeline for 3 years with 20 viruses per month saving intermediate files in `data/` with the prefix `test_`.  Fractions of the pipeline can be loaded as follows

`python src/H3N2_process -y 3 -v 20 --prefix data/test_  --start align --stop refine`

this would load previously saved virus dict from file (with prefix `test_`) and continue through the steps `align`, `tree`, `refine`. Available steps are

```
    all_steps = ['filter', 'align', 'clean', 'tree', 'ancestral', 'refine', 'frequencies', 'export']
```

where the last element corresponds to writing the results as jsons to auspice. I typically run this from the ipython command line with the flag `--test`, which only loads. Individual steps and methods can then be called from within ipython.
### Issues
- genotype output is now mutation pairs as in 159F/225D -> auspice needs updating
- delimit_newick is influenza A specific.

### CODE REVIEW

**Comment by rneher** [comment]
the auspice change should be pretty easy. just didn't want to mess around with it before we merge your changes to the design.

**Comment by trvrb** [comment]
I just screwed this up.

**Comment by trvrb** [comment]
Hmm... I think it's okay. Just a dirty history.

**Comment by trvrb** [comment]
I'm not sure I'm understanding the difference between `genotypes` and `mutations` in `frequencies.json`.

**Comment by trvrb** [comment]
I get it. Mutations are single and genotypes are double (used to allow double or more).

**Comment by rneher** [comment]
exactly. there isn't really a good reason to keep them separate. just depends on how we want to do the parsing in auspice. re fasta_fields: it thought I had made them default, but maybe I got confused again. default is good.

**Comment by rneher** [comment]
sorry about this ]. I had truncated the regions after global for testing and forgot to remove this terminating bracket

**Comment by trvrb** [comment]
Here's the tree I just got for default parameters:

nextflu-3-3

Everything ran very smoothly.

**Comment by trvrb** [comment]
Thanks @rneher for doing an amazing job with this.

**Comment by rneher** [comment]
I am not sure the genotype parsing is correct as is. is going to be smth like gt = ['159Y', '225D']. the labels of the genotype json are 159Y/225D. it looks up 159Y in genotypes. which will fail, but then finds it in mutations and plots the mutation frequency:

```
        if (json["genotypes"][region][gt[0]]!=undefined) {
            for (var pi=0; pi<freq.length; pi++){
                freq[pi]+=json["genotypes"][region][gt[0]][pi];
            }
        }else if (json["mutations"][region][gt[0]]!=undefined) {
            for (var pi=0; pi<freq.length; pi++){
                freq[pi]+=json["mutations"][region][gt[0]][pi];
            }
```

we can join the genotype fields sorted by position with '/' and it should work.

**Comment by rneher** [comment]
I just fixed this.

**Pull request merged**
